###
POST http://localhost:3000/item/create HTTP/1.1
Content-Type: application/json
 
{
    "name": "conjunto de mesa com 4 cadeiras ",
    "price": "R$ 8,00" ,
    "color": "Branca", 
    "dimenson": "70x70x70cm"
}


### 
GET http://localhost:3000/item/read HTTP/1.1
Content-Type: application/json


###
PUT http://localhost:3000/item/upd/1 HTTP/1.1
Content-Type: application/json
 
{
    "name": "conjunto de mesa com 4 cadeiras ",
    "price":"R$ 11,00" ,
    "color":"Branca", 
    "dimenson":"70x70x70cm"
}
###
DELETE  http://localhost:3000/item/del/0 HTTP/1.1
Content-Type: application/json

