###
POST http://localhost:3001/cart/create HTTP/1.1
Content-Type: application/json

{
    "items": [
        {
            "item_id":1,
            "qtd":2
        },
        {
            "item_id":7,
            "qtd":100
        }
    ]
}


###
GET http://localhost:3001/cart/read HTTP/1.1
Content-Type: application/json
 
###
GET http://localhost:3001/cart/show/2 HTTP/1.1
Content-Type: application/json
 
###
PUT http://localhost:3001/cart/update/2 HTTP/1.1
Content-Type: application/json
 
{
    "items": [
        {
            "item_id":1,
            "qtd":2
        },
        {
            "item_id":7,
            "qtd":100
        }
    ]
}

###
DELETE http://localhost:3001/cart/delete/1 HTTP/1.1
Content-Type: application/json
 
 
 
 