###
POST http://localhost:3001/item/create HTTP/1.1
Content-Type: application/json
 
{
    "name": "Mini Sanduíces Gourmet",
    "decorations": "Cesta de Futebol",
    "items": "Cadeira Infantil",
    "food": "Suco de Frutas",
    "imagem": "https://i.imgur.com/Ll2EXcZ.jpeg" 
}

###
GET http://localhost:3001/item/show/29 HTTP/1.1
Content-Type: application/json


### 
GET http://localhost:3001/item/read HTTP/1.1
Content-Type: application/json



###
PUT http://localhost:3001/item/upd/1 HTTP/1.1
Content-Type: application/json
 
{
 "name": "Decoração de Casamento",
 "decorations": "Cesta de Futebol",
 "items": "Cadeira Infantil",
 "food": "Suco dx Frutas"
}

###
DELETE  http://localhost:3001/item/del/3 HTTP/1.1
Content-Type: application/json

