### type create - protocolo http - endereço:porta - rota do objeto
POST http://localhost:3001/party/create HTTP/1.1
Content-Type: application/json

{   "name": "Decoração de Futebol",
    "decorations": "Cesta de Futebol",
    "cart_id": 1
    "user_id": 1
    "food": "Suco de Frutas"
}

###
GET http://localhost:3001/party/read HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:3001/party/update/2 HTTP/1.1
Content-Type: application/json

{
 "name": "Decoração de Casamento",
 "decorations": "Cesta de Futebol",
 "items": "Cadeira Infantil",
 "food": "Suco dx Frutas"
}

###
DELETE http://localhost:3001/party/del/1 HTTP/1.1
Content-Type: application/json


### cadastrar produtos, min 5
