### type create - protocolo http - endereço:porta - rota do objeto
POST http://localhost:3000/party/create HTTP/1.1
Content-Type: application/json

{
    "decorations": "Futebol",
    "items": "cadeiras e mesas",
    "food": "salgada"
}

###
GET http://localhost:3000/party/read HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:3000/party/update/0 HTTP/1.1
Content-Type: application/json

{
 "decorations": "Sonic",
 "items": "toalha",
 "food": "doce"
}

###
DELETE http://localhost:3000/party/del/1 HTTP/1.1
Content-Type: application/json
