### exemplo de create de festa com cartão e exemplo de create de festa com pix
POST http://localhost:3001/party/create HTTP/1.1
Content-Type: application/json

{
    "name": "Festa Infantil",
    "cart_id": 1,
    "user_id": 1,
    "tipo_pag": "cartao",
    "cpf_cnpj":"999.999.999-99",
    "nome_cartao":"nuu",
    "numero_cartao":"9999 9999 9999 9999",
    "validade":"99/99",
    "CVV":"999",
    "valor": 2000
}

### type create - protocolo http - endereço:porta - rota do objeto
POST http://localhost:3001/party/create HTTP/1.1
Content-Type: application/json

{
    "name": "Festa Infantil",
    "cart_id": 1,
    "user_id": 1,
    "tipo_pag": "pix",
    "valor": 2000
}

###
GET http://localhost:3001/party/read HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:3001/party/update/18 HTTP/1.1
Content-Type: application/json

{
    "name": "Festa Infantil",
    "cart_id": 1,
    "user_id": 1,
    "pix": "pix",
    "cpf_cnpj":"",
    "nome_cartao":"",
    "numero_cartao":"",
    "validade":"",
    "CVV":""
}

###
DELETE http://localhost:3001/party/del/18 HTTP/1.1
Content-Type: application/json


### cadastrar produtos, min 5
